services:
  hotel-service-db:
    extends:
      service: hotel-service-db
      file: ./HotelService/docker-compose.yml

  reservation-service-db:
    extends:
      service: reservation-service-db
      file: ./ReservationService/docker-compose.yml

  hotel-service:
    extends:
      service: hotel-service
      file: ./HotelService/docker-compose.yml

  reservation-service:
    extends:
      service: reservation-service
      file: ./ReservationService/docker-compose.yml

networks:
  hotel_network:
    driver: bridge